---
title: "Welcome to this class!"
format: html
editor: visual
---

This website will walk you through the tutorials for the *Introduction to R* course of Ecole Polytechnique's Master program. The course has 3 main objectives: (i) know the basics of R (ii) manipulate the standard statistical and empirical tools (iii) make appealing output.

> **Practical information**
>
> **TA**: [Mateo Moglia](https://mateomoglia.github.io)
>
> **Schedule**: 2 sessions of 4 hours. Check Moodle before class in case of any change in classroom.
>
> **Required software**: R and its IDE, RStudio (all free). You may download it [here](https://posit.co/download/rstudio-desktop/). Create a free account to use [Overleaf](https://www.overleaf.com). Bring you own laptop or use the lab's computer. The data used in the tutorials are on Moodle.
>
> **Rules**: Send me an email if you miss the class. You are grown-up adults, I trust you to follow thoroughly the class. Do not hesitate to work in small groups.
>
> **Data**: Data are [here](https://drive.google.com/drive/folders/1mNXjRVWK4-5ZcgrYdNgevgxV25byMHPL?usp=sharing)
>
> **Evaluation**: There is no evaluation.

::: {.callout-caution collapse="true"}
## Log

-   v0.0 - 20/08/25 - Creation
:::

## Class outline

-   Part 0: First hand on R
    -   Discover R and its IDE, RStudio
    -   `tidyverse` environment and packages
-   Part 1: Open data
    -   Open and manipulate data
-   Part 2: Descriptive statistics
    -   Compute descriptive statistics
    -   Export them in `.tex`
    -   Linear regression
-   Part 3: Data visualization
    -   Scatter plots
    -   Bar charts
    -   Linear regression
    -   Density and box plots
-   Part 4: Spatial data manipulation
    -   Shapefiles
    -   Compute distances
    -   Maps

During sessions, I will walk you through all materials covered here. I provide some exercises that you are required to perform.

## About this site and my inspirations

I created this site for teaching purpose. It is of course perfectible and any constructive comment is more than welcome ([write me an email!](mailto:mateo.moglia@gmail.com)). I took inspiration from these sources:

-   The great [Florian Oswald](https://floswald.github.io) teaching material at Sciences Po. Do not hesitate to check his teaching material (in English)

-   The [tutorials](https://mtes-mct.github.io/parcours-r/) of the French Ministry of Ecology (in French)

-   The infamous online book [Econometrics with R](https://www.econometrics-with-r.org) (in English)